"""Package the V15 search bot into a single self-contained Kaggle submission.

Output: submission_v15.py — one file, standard libs + numpy + numba only.
The four V15 modules are embedded (base64) and registered as in-memory modules;
the V7 weights are embedded and written to a temp file at import time.

Behavior is byte-identical to the local v15_search bot (verified by a self-test
at the end of packaging). If numba is unavailable on Kaggle, the submission
degrades gracefully to pure V7 instead of crashing.

Run:
    python package_v15.py
"""

from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "submission_v15.py"

MODULES = ["bot_v7", "v15_fast_sim", "v15_eval", "v15_bc", "v15_search"]
WEIGHTS = ROOT / "evaluations" / "scorer_v7_kaggle.npz"


def _patch(name: str, src: str) -> str:
    if name == "bot_v7":
        old = ('_DEFAULT_TRAINING_CHECKPOINT = Path(__file__).resolve().parent '
               '/ "evaluations" / "scorer_v7_kaggle.npz"')
        new = "_DEFAULT_TRAINING_CHECKPOINT = Path(__v15_weights_path__)"
        if old not in src:
            raise RuntimeError("bot_v7 checkpoint line not found — packaging aborted")
        src = src.replace(old, new)
    return src


def build() -> str:
    weights_b64 = base64.b64encode(WEIGHTS.read_bytes()).decode("ascii")
    enc = {}
    for name in MODULES:
        src = (ROOT / f"{name}.py").read_text(encoding="utf-8")
        src = _patch(name, src)
        enc[name] = base64.b64encode(src.encode("utf-8")).decode("ascii")

    parts = []
    parts.append('"""V15 search bot — self-contained Kaggle submission.\n')
    parts.append("Generated by package_v15.py. Identical policy to the P2/P3 smoke runs.\n")
    parts.append('Falls back to pure V7 if numba is unavailable.\n"""\n')
    parts.append("import base64, os, sys, tempfile, types\n")
    parts.append("import numpy as np\n\n")

    parts.append(f'_WEIGHTS_B64 = "{weights_b64}"\n')
    parts.append("__v15_weights_path__ = os.path.join(tempfile.gettempdir(), "
                 '"scorer_v7_kaggle.npz")\n')
    parts.append("try:\n")
    parts.append("    with open(__v15_weights_path__, 'wb') as _f:\n")
    parts.append("        _f.write(base64.b64decode(_WEIGHTS_B64))\n")
    parts.append("except Exception:\n    pass\n\n")

    parts.append("_MODULE_SRC = {\n")
    for name in MODULES:
        parts.append(f'    "{name}": "{enc[name]}",\n')
    parts.append("}\n\n")

    parts.append("def _register(name, inject=None):\n")
    parts.append("    m = types.ModuleType(name)\n")
    parts.append("    m.__dict__['__name__'] = name\n")
    parts.append("    if inject:\n        m.__dict__.update(inject)\n")
    parts.append("    src = base64.b64decode(_MODULE_SRC[name]).decode('utf-8')\n")
    parts.append("    sys.modules[name] = m  # register before exec: @dataclass needs it\n")
    parts.append("    exec(compile(src, name + '.py', 'exec'), m.__dict__)\n")
    parts.append("    return m\n\n")

    parts.append("_register('bot_v7', inject={'__v15_weights_path__': __v15_weights_path__})\n")
    parts.append("_SEARCH_OK = False\n")
    parts.append("try:\n")
    parts.append("    _register('v15_fast_sim')\n")
    parts.append("    _register('v15_eval')\n")
    parts.append("    _register('v15_bc')\n")
    parts.append("    _register('v15_search')\n")
    parts.append("    _SEARCH_OK = True\n")
    parts.append("except Exception:\n    _SEARCH_OK = False\n\n")

    parts.append("import bot_v7 as _v7\n")
    parts.append("if _SEARCH_OK:\n    import v15_search as _vs\n\n")

    parts.append("def agent(obs, config=None):\n")
    parts.append("    if _SEARCH_OK:\n")
    parts.append("        try:\n")
    # ~0.7s/move: Kaggle's per-move base limit is ~1s, with a 60s-per-GAME
    # overage bank. Staying under 1s/move keeps the bank intact for the whole
    # game. n_rollouts is just a cap; the time budget cuts it.
    parts.append("            return _vs.search(obs, config, time_budget=0.7, horizon=24)\n")
    parts.append("        except Exception:\n            pass\n")
    parts.append("    try:\n")
    parts.append("        return _v7.agent(obs, config)\n")
    parts.append("    except Exception:\n        return []\n")

    return "".join(parts)


def selftest() -> None:
    """Verify the packaged submission runs the search end-to-end (no numba,
    no crash) and produces valid moves on real states."""
    import importlib
    import random

    import numpy as np
    import v14_core
    from local_simulator.official_fast import OfficialFastGame

    sub = importlib.import_module("submission_v15")
    if not sub._SEARCH_OK:
        raise RuntimeError("self-test FAILED: _SEARCH_OK is False (search disabled)")

    checks = 0
    for seed, n_players in ((101, 2), (202, 4)):
        random.seed(seed)
        np.random.seed(seed)
        g = OfficialFastGame(n_players, seed=seed, episode_steps=120,
                             use_c_accel=False)
        for _ in range(40):
            g.step([[] for _ in range(n_players)])
        obs = v14_core.obs_as_dict(g.observation(0))
        mv = sub.agent(dict(obs), g.configuration)
        if not isinstance(mv, list):
            raise RuntimeError(f"self-test FAILED: agent returned {type(mv)}")
        checks += 1
        print(f"  state {seed} {n_players}p: agent returned {len(mv)} launches")
    print(f"self-test OK: search active, {checks}/{checks} states played cleanly")


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.name} ({size_kb:.1f} KB)")
    selftest()
