"""Package V20 into a self-contained Kaggle submission.

Output: submission_v20_2p.py

This packages the local V20 stack plus its V15/V7 dependencies into one file.
The generated agent uses the V20 defaults that validated 12/12 in the local
2p bench against raw V15.
"""

from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "submission_v20_2p.py"

MODULES = [
    "bot_v7",
    "v15_fast_sim",
    "v15_eval",
    "v15_bc",
    "v15_search",
    "v20_rank_value",
    "v20_macro",
    "v20_support",
    "v20_search",
    "v20_agent",
]
WEIGHTS = ROOT / "evaluations" / "scorer_v7_kaggle.npz"


def _patch(name: str, src: str) -> str:
    if name == "bot_v7":
        old = (
            '_DEFAULT_TRAINING_CHECKPOINT = Path(__file__).resolve().parent '
            '/ "evaluations" / "scorer_v7_kaggle.npz"'
        )
        new = "_DEFAULT_TRAINING_CHECKPOINT = Path(__v20_weights_path__)"
        if old not in src:
            raise RuntimeError("bot_v7 checkpoint line not found")
        src = src.replace(old, new)
    return src


def build() -> str:
    weights_b64 = base64.b64encode(WEIGHTS.read_bytes()).decode("ascii")
    enc: dict[str, str] = {}
    for name in MODULES:
        src = (ROOT / f"{name}.py").read_text(encoding="utf-8")
        src = _patch(name, src)
        enc[name] = base64.b64encode(src.encode("utf-8")).decode("ascii")

    parts: list[str] = []
    parts.append('"""V20 2p search bot - self-contained Kaggle submission.\n')
    parts.append("Generated by package_v20_2p.py from the local V20 stack.\n")
    parts.append("Validated locally at 12/12 in 2p against raw V15.\n")
    parts.append('"""\n')
    parts.append("import base64, os, sys, tempfile, types\n")
    parts.append("import numpy as np\n\n")

    parts.append(f'_WEIGHTS_B64 = "{weights_b64}"\n')
    parts.append(
        "__v20_weights_path__ = os.path.join(tempfile.gettempdir(), "
        '"scorer_v7_kaggle.npz")\n'
    )
    parts.append("try:\n")
    parts.append("    with open(__v20_weights_path__, 'wb') as _f:\n")
    parts.append("        _f.write(base64.b64decode(_WEIGHTS_B64))\n")
    parts.append("except Exception:\n")
    parts.append("    pass\n\n")

    parts.append("_MODULE_SRC = {\n")
    for name in MODULES:
        parts.append(f'    "{name}": "{enc[name]}",\n')
    parts.append("}\n\n")

    parts.append("def _register(name, inject=None):\n")
    parts.append("    m = types.ModuleType(name)\n")
    parts.append("    m.__dict__['__name__'] = name\n")
    parts.append("    if inject:\n")
    parts.append("        m.__dict__.update(inject)\n")
    parts.append("    src = base64.b64decode(_MODULE_SRC[name]).decode('utf-8')\n")
    parts.append("    sys.modules[name] = m\n")
    parts.append("    exec(compile(src, name + '.py', 'exec'), m.__dict__)\n")
    parts.append("    return m\n\n")

    parts.append("_V20_OK = False\n")
    parts.append("try:\n")
    parts.append("    _register('bot_v7', inject={'__v20_weights_path__': __v20_weights_path__})\n")
    for name in MODULES[1:]:
        parts.append(f"    _register('{name}')\n")
    parts.append("    _V20_OK = True\n")
    parts.append("except Exception:\n")
    parts.append("    _V20_OK = False\n\n")

    parts.append("try:\n")
    parts.append("    import v20_agent as _v20\n")
    parts.append("except Exception:\n")
    parts.append("    _v20 = None\n")
    parts.append("try:\n")
    parts.append("    import v15_search as _v15\n")
    parts.append("except Exception:\n")
    parts.append("    _v15 = None\n")
    parts.append("try:\n")
    parts.append("    import bot_v7 as _v7\n")
    parts.append("except Exception:\n")
    parts.append("    _v7 = None\n\n")

    parts.append("def agent(obs, config=None):\n")
    parts.append("    if _V20_OK and _v20 is not None:\n")
    parts.append("        try:\n")
    parts.append("            return _v20.agent(obs, config, time_budget=0.70, horizon=22)\n")
    parts.append("        except Exception:\n")
    parts.append("            pass\n")
    parts.append("    if _v15 is not None:\n")
    parts.append("        try:\n")
    parts.append("            return _v15.search(obs, config, time_budget=0.70, horizon=24)\n")
    parts.append("        except Exception:\n")
    parts.append("            pass\n")
    parts.append("    if _v7 is not None:\n")
    parts.append("        try:\n")
    parts.append("            return _v7.agent(obs, config)\n")
    parts.append("        except Exception:\n")
    parts.append("            pass\n")
    parts.append("    return []\n")
    return "".join(parts)


def selftest() -> None:
    import importlib.util

    import v14_core
    from local_simulator.official_fast import OfficialFastGame

    spec = importlib.util.spec_from_file_location("submission_v20_2p", OUT)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot import generated submission")
    sub = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(sub)
    if not getattr(sub, "_V20_OK", False):
        raise RuntimeError("self-test failed: V20 modules did not load")

    for seed, n_players in ((101, 2), (202, 4)):
        game = OfficialFastGame(n_players, seed=seed, episode_steps=120, use_c_accel=False)
        for _ in range(25):
            game.step([[] for _ in range(n_players)])
        obs = v14_core.obs_as_dict(game.observation(0))
        move = sub.agent(dict(obs), game.configuration)
        if not isinstance(move, list):
            raise RuntimeError(f"agent returned {type(move)}")
        print(f"  smoke {n_players}p seed={seed}: {len(move)} launches")


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.name} ({OUT.stat().st_size / 1024:.1f} KB)")
    selftest()
